<a href="https://colab.research.google.com/github/matteogolfarelli/DataCentricAI/blob/main/Data%20Understanding/CarEvaluationEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np

#------------------------------------------------------------- Data loading and Data frame creation
url = "https://raw.githubusercontent.com/matteogolfarelli/DataCentricAI/main/Data%20Understanding/CarEvaluation.csv"
df = pd.read_csv(url)

print("The dataset contains ", len(df), "tuple")
print("\n")
print(df.head(), df.tail()) # Show the first five lines
print("\n")

#------------------------------------------------------------- Data preprocessing
target_col = "class"

X = df.drop(columns=target_col)
y = df[target_col]
print("\n ")
print(df.head)
print("\n ------------------- Features: sample tuples \n")
print(X.head)
print("\n ------------------- Class: sample tuples \n")
print(y.head)

The dataset contains  1728 tuple


  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc      buying maint  doors persons lug_boot safety  class
1723    low   low  5more    more      med    med   good
1724    low   low  5more    more      med   high  vgood
1725    low   low  5more    more      big    low  unacc
1726    low   low  5more    more      big    med   good
1727    low   low  5more    more      big   high  vgood



 
<bound method NDFrame.head of      buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    lo

In [4]:
# Apply Label Encoding to each individual column of X

from sklearn.preprocessing import LabelEncoder
import pandas as pd

X_encoded = pd.DataFrame()
for column in X.columns:
    encoder = LabelEncoder()
    X_encoded[column] = encoder.fit_transform(X[column])

In [5]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
import numpy as np

# Define the ordered categories for each feature
categories = [
    ['low', 'med', 'high', 'vhigh'],  # buying
    ['low', 'med', 'high', 'vhigh'],  # maint
    ['2', '3', '4', '5more'],      # doors
    ['2', '4', 'more'],             # persons
    ['small', 'med', 'big'],        # lug_boot
    ['low', 'med', 'high']          # safety
]

# Initialize OrdinalEncoder with the specified categories
# handle_unknown='use_encoded_value' and unknown_value=np.nan allow for handling values not in categories
encoder = OrdinalEncoder(categories=categories, handle_unknown='use_encoded_value', unknown_value=np.nan)

# Apply Ordinal Encoding to the X DataFrame
X_encoded = pd.DataFrame(encoder.fit_transform(X), columns=X.columns)

In [6]:
print("\n ------------------- Encoded Features (Ordinal): sample tuples \n")
print(X_encoded.head())


 ------------------- Encoded Features (Ordinal): sample tuples 

   buying  maint  doors  persons  lug_boot  safety
0     3.0    3.0    0.0      0.0       0.0     0.0
1     3.0    3.0    0.0      0.0       0.0     1.0
2     3.0    3.0    0.0      0.0       0.0     2.0
3     3.0    3.0    0.0      0.0       1.0     0.0
4     3.0    3.0    0.0      0.0       1.0     1.0


In [7]:
# Apply OneHot Encoding to categorical features in X

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_encoded = encoder.fit_transform(X)

In [8]:
print("\n ------------------- Encoded Features: sample tuples \n")
print(X_encoded)


 ------------------- Encoded Features: sample tuples 

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 1. 0. 0.]]


In [9]:
#------------------------------------------------------------- Decision tree: Model training and testing with split

from sklearn.tree import DecisionTreeClassifier, plot_tree

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42, stratify=y)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

# Predizioni sul test set
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred, average='macro'))
print("Recall: ", recall_score(y_test, y_pred, average='macro'))
print("F1-score: ", f1_score(y_test, y_pred, average='macro'))

[[106   2   7   0]
 [  2  19   0   0]
 [  7   0 356   0]
 [  0   2   0  18]]
Accuracy:  0.9614643545279383
Precision:  0.932135585100012
Recall:  0.9268043221600534
F1-score:  0.928365042141826


In [10]:
from sklearn.neighbors import KNeighborsClassifier

#------------------------------------------------------------- KNearestNeighbors: Model training and testing with split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42, stratify=y)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

# Predizioni sul test set
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred, average='macro'))
print("Recall: ", recall_score(y_test, y_pred, average='macro'))
print("F1-score: ", f1_score(y_test, y_pred, average='macro'))

[[ 97   0  18   0]
 [ 13   7   1   0]
 [ 10   0 353   0]
 [  8   1   2   9]]
Accuracy:  0.8978805394990366
Precision:  0.8941656918449198
Recall:  0.6498158462091269
F1-score:  0.7149349425325865
